game_size : 3     # board size
iterations: 1000  # number of iterations of mcts + training + arena

# MCTS parameters
mcts_parameters:
  n_games                   : 50
  n_simulations             : 20
  temperature_move_threshold: 5
  c_puct                    : 1    # PUCT algorithm parameter, used in MCTS: select

# neural network parameters
model_parameters:
  hidden_units  : 128
  hidden_layers : 2
  dropout       : 0.2
  initialize_gain: 0.1

# neural network training: optimizer parameters
optimizer_parameters:
  learning_rate: 0.1
  momentum     : 0.9

# neural network training: training parameters
training_parameters:
  dataset_size: 50000  # includes rotations and reflections
  epochs      : 100000
  batch_size  : 32
  patience    : 100

# arena (model comparison) parameters
arena_parameters:
  n_games     : 1000
  win_fraction: 0.55



